### ISSUE TITLE
Installation process ends with no result (not installed and error)

### ISSUE THREAD

**Issue by lluisvicens** [havatv/qgisclimbplugin#1]
Hi Håvard, 
I've just installed your plugin into QGIS 3.6 ([qgis_version.txt](https://github.com/havatv/qgisclimbplugin/files/2941822/qgis_version.txt)) onto a Linux Mint 19 Tara, and after the installation process I can't see it, and it is not visible in the processing toolbox. By the way, no error message appears. Then, when I try to uninstall or reinstall the plugin, it appears the following message ([reinstall_plugin_error.txt](https://github.com/havatv/qgisclimbplugin/files/2941816/reinstall_plugin_error.txt)).

thanks!
best regards,
Lluís

**Comment by havatv** [comment]
Thanks for reporting, @lluisvicens.
The problem could be that I have set the QGIS minimum version to 3.4.5.  I will try to change this to 3.4.
Update: After changing the minimum QGIS version to 3.4, the plugin became visible in the plugin manager.
After installation I had to restart QGIS in order to make it show in the processing toolbox.

**Comment by lluisvicens** [comment]
Thanks for this great plugin @havatv and your kind reply. Now I've just updated my 3.4 to 3.6 and the plugin is correctly installed. It also appears on the processing toolbox. In any case, I cant' make it work, unless I'll do it from the «Run as batch process option». This in not a big problem but from the main window, when I click on the «Run» button, nothing happens. When I try the batch process, I get the correct result.

Many thanks for your time and such a big effort on this.

**Comment by havatv** [comment]
Strange.  With QGIS 3.4.5 (LTR), I can start it using the "Run" button (I am on Ubuntu 18.04). I don't know what might cause the strange behaviour you experience.

**Comment by havatv** [comment]
Since the installation now seems to work, I close this issue.  Can you open a new issue with the "run" problem?
