### ISSUE TITLE
«Run» button doesn't work when clicked

### ISSUE THREAD

**Issue by lluisvicens** [havatv/qgisclimbplugin#2]
Hi,
I already installed **Climb along line** plugin on [QGIS 3.6](https://github.com/qgis/QGIS/commit/5873452) in a Linux Mint 19. Once I open the plugin window and I set the parameters, click on «Run» button doesn't have any effect (not even an error message).

Otherwise, If I run the command from the batch processing, it works correctly:
```

Processing algorithm 1/1…
Algorithm Climb along line starting…
Input parameters:
{'BANDDEM': 1,
'DEMFORZ': 'mde_stjulia',
'INPUT': 'Updated',
'OUTPUT': <QgsProcessingOutputLayerDefinition {'sink':/home/lluis/climbingUpdated.gpkg, 'createOptions': {}}>}

Adding Z values from DEM...
Results: {'OUTPUT': 'output_96f9171c_5d37_49ed_9d54_4b7cbde5d8ba'}
Z values added.
Algorithm Climb along line correctly executed…
Execution completed in 0.03 seconds
Results:
{'OUTPUT': '/home/lluis/climbingUpdated.gpkg',
'TOTALCLIMB': 311.0799865722656,
'TOTALDESCENT': 245.66998672485352}

Loading resulting layers
Batch execution completed in 0.06 seconds
```
Thanks!

**Comment by havatv** [comment]
Thanks, @lluisvicens.
Are you able to run other plugins using the "run" button? If so, can you provide their names?
Have you checked if there is any output in the "Log messages" panel?

**Comment by lluisvicens** [comment]
Yes, I'm able to use the «run» button in every single plugin (i.e. Network, Visibility Analysis among others) or any single tool implemented in the processing tool as Climbalongline is. Regarding to the second question, there isn't any kind output in the Log panel (General, Plugins, Python warning nor Messages).

**Comment by lluisvicens** [comment]
I've just updated the Climb plugin to the newest version (https://plugins.qgis.org/plugins/Climb/version/1.0.2/) you recently uploaded to the repository and now it works smoothly!! The Run button is now ok! Great job! Thanks!

**Comment by havatv** [comment]
Great to hear - thanks!
I close the issue.
